# Generated by Django 5.1.1 on 2024-11-28 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primerApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcg',
            name='codigo',
        ),
    ]
