# Generated by Django 5.1.1 on 2024-11-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerApp', '0002_remove_solicitudcg_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcg',
            name='codigo',
            field=models.CharField(default='1', editable=False, max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
