# Generated by Django 5.1.1 on 2024-11-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerApp', '0003_solicitudcg_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='integra',
            name='estadoPago',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='integra',
            name='fecha_union',
            field=models.DateTimeField(),
        ),
    ]
