# Generated by Django 5.1.1 on 2024-12-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerApp', '0004_integra_estadopago_alter_integra_fecha_union'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcg',
            name='codigo',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
    ]
