# Generated by Django 5.1.1 on 2024-12-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerApp', '0005_alter_solicitudcg_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcg',
            name='contactoEmergenciaNombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='solicitudcg',
            name='contactoEmergenciaTelefono',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='solicitudcg',
            name='correoElectronico',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='solicitudcg',
            name='nombreCompleto',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='solicitudcg',
            name='rut',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='solicitudcg',
            name='telefono',
            field=models.CharField(max_length=150),
        ),
    ]
