# Generated by Django 5.1.1 on 2024-12-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerApp', '0006_alter_solicitudcg_contactoemergencianombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcg',
            name='codigo',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
