# Generated by Django 5.1.1 on 2024-12-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerApp', '0009_alter_solicitudcg_contactoemergencianombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasegrupal',
            name='estatus_llenado',
            field=models.BooleanField(default=False),
        ),
    ]
