# Generated by Django 5.1.1 on 2024-12-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerApp', '0010_clasegrupal_estatus_llenado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombreCompleto',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
